version: '3.8'

services:
  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data

  rate-limiter:
    build: .
    ports:
      - "8080:8080"
    env_file:
      - .env
    depends_on:
      - redis

volumes:
  redis-data:
